/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen2p2_venuslobo;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author ADMIN
 */
public class Principal extends javax.swing.JFrame {

    private DefaultTreeModel DefaultTreeModel;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pop = new javax.swing.JPopupMenu();
        pop_agregar = new javax.swing.JMenuItem();
        pop_limpiar = new javax.swing.JMenuItem();
        pop_salir = new javax.swing.JMenuItem();
        pop_tree = new javax.swing.JPopupMenu();
        pop_favoritos = new javax.swing.JMenuItem();
        pop_eliminar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        panel_vehiculo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        texto_anio = new javax.swing.JTextField();
        texto_marca = new javax.swing.JTextField();
        texto_modelo = new javax.swing.JTextField();
        date = new com.toedter.calendar.JDateChooser();
        texto_precio = new javax.swing.JTextField();
        codi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tree_vehiculo = new javax.swing.JTree();
        jLabel8 = new javax.swing.JLabel();
        box = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_vehiculo = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        boton_agregar = new javax.swing.JButton();

        pop_agregar.setText("Agregar vehiculo");
        pop_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pop_agregarActionPerformed(evt);
            }
        });
        pop.add(pop_agregar);

        pop_limpiar.setText("Limpiar casillas");
        pop_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pop_limpiarActionPerformed(evt);
            }
        });
        pop.add(pop_limpiar);

        pop_salir.setText("Salir");
        pop_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pop_salirActionPerformed(evt);
            }
        });
        pop.add(pop_salir);

        pop_favoritos.setText("Agregar a favoritos");
        pop_favoritos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pop_favoritosActionPerformed(evt);
            }
        });
        pop_tree.add(pop_favoritos);

        pop_eliminar.setText("Eliminar");
        pop_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pop_eliminarActionPerformed(evt);
            }
        });
        pop_tree.add(pop_eliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_vehiculo.setBackground(new java.awt.Color(153, 153, 153));
        panel_vehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_vehiculoMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("NUEVO VEHICULO");

        jLabel2.setText("Codigo");

        jLabel3.setText("Anio");

        jLabel4.setText("Marca");

        jLabel5.setText("Modelo");

        jLabel6.setText("Fecha");

        jLabel7.setText("Precio");

        texto_anio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto_anioActionPerformed(evt);
            }
        });

        date.setDateFormatString("MM/dd/yyyy");

        codi.setText("jLabel11");

        javax.swing.GroupLayout panel_vehiculoLayout = new javax.swing.GroupLayout(panel_vehiculo);
        panel_vehiculo.setLayout(panel_vehiculoLayout);
        panel_vehiculoLayout.setHorizontalGroup(
            panel_vehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_vehiculoLayout.createSequentialGroup()
                .addGroup(panel_vehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_vehiculoLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel1))
                    .addGroup(panel_vehiculoLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(panel_vehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_vehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(panel_vehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(texto_anio)
                            .addComponent(texto_marca)
                            .addComponent(texto_modelo)
                            .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(texto_precio)
                            .addComponent(codi))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        panel_vehiculoLayout.setVerticalGroup(
            panel_vehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_vehiculoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_vehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(codi))
                .addGap(18, 18, 18)
                .addGroup(panel_vehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(texto_anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_vehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(texto_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_vehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(texto_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_vehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_vehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(texto_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Vehiculos");
        tree_vehiculo.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        tree_vehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tree_vehiculoMouseClicked(evt);
            }
        });
        tree_vehiculo.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                tree_vehiculoValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(tree_vehiculo);

        jLabel8.setText("Vehiculos existentes");

        box.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boxItemStateChanged(evt);
            }
        });
        box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxActionPerformed(evt);
            }
        });

        jLabel9.setText("Favoritos");

        tabla_vehiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Anio", "Marca", "Modelo", "Fecha", "Precio"
            }
        ));
        jScrollPane2.setViewportView(tabla_vehiculo);

        jLabel10.setText("Tedalles del vehiculo seleccionado");

        boton_agregar.setText("Exportar al txt");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(panel_vehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel8)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(153, 153, 153))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(box, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(204, 204, 204)
                                .addComponent(boton_agregar)))
                        .addContainerGap(26, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(panel_vehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(boton_agregar)
                                .addGap(45, 45, 45))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33))))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 366));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void texto_anioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_anioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_anioActionPerformed

    private void boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxActionPerformed

    private void panel_vehiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_vehiculoMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            pop.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_panel_vehiculoMouseClicked

    private void pop_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pop_agregarActionPerformed
        // TODO add your handling code here:

        String anioTexto = texto_anio.getText();
        String marca = texto_marca.getText();
        String mdelo = texto_modelo.getText();
        String precioTexto = texto_precio.getText();
        Date creacion = date.getDate();

        //validar que todos los campos este llenos 
        if (anioTexto.isEmpty()
                || marca.isEmpty()
                || mdelo.isEmpty()
                || precioTexto.isEmpty()
                || creacion == null) {
            JOptionPane.showMessageDialog(this, "Llene todos los campos");
        } else {
            //hacer unos cambios con algunas variables 
            int anio = Integer.parseInt(anioTexto);
            double precio = Double.parseDouble(precioTexto);

            //crear el nuevo vehiculo 
            vehiculo nuevoVehiculo = new vehiculo(anio, marca, mdelo, precio, creacion);
            //agregar al arraylist
            vehiculos.add(nuevoVehiculo);

            JOptionPane.showMessageDialog(this, "Vehiculo agregado");

            //aregar al arbol 
            DefaultTreeModel modeloARBOL = (DefaultTreeModel) tree_vehiculo.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloARBOL.getRoot();

            int ani;
            vehiculo modelo;

            ani = nuevoVehiculo.getAnio();
            modelo = nuevoVehiculo;

            DefaultMutableTreeNode nodoAnioExistente = null;
            for (int i = 0; i < raiz.getChildCount(); i++) {
                DefaultMutableTreeNode nodoAnio = (DefaultMutableTreeNode) raiz.getChildAt(i);
                if (nodoAnio.getUserObject().equals(ani)) {
                    nodoAnioExistente = nodoAnio;
                    break;
                }
            }

            if (nodoAnioExistente == null) {
                nodoAnioExistente = new DefaultMutableTreeNode(ani);
                raiz.add(nodoAnioExistente);
                modeloARBOL.reload();
            }

            //agregar el modelo al nodo 
            DefaultMutableTreeNode nodoModelo = new DefaultMutableTreeNode(modelo);
            nodoAnioExistente.add(nodoModelo);
            modeloARBOL.reload();

        }
    }//GEN-LAST:event_pop_agregarActionPerformed

    private void pop_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pop_limpiarActionPerformed
        // TODO add your handling code here:

        codi.setText("");
        texto_anio.setText("");
        texto_marca.setText("");
        texto_modelo.setText("");
        texto_precio.setText("");
        date.setDate(new Date());
    }//GEN-LAST:event_pop_limpiarActionPerformed

    private void pop_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pop_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_pop_salirActionPerformed

    private void tree_vehiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tree_vehiculoMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
             //seleccionar un nodo con click derecho
            int row = tree_vehiculo.getClosestRowForLocation(evt.getX(), evt.getY());
            tree_vehiculo.setSelectionRow(row);
            Object v1 = tree_vehiculo.getSelectionPath().getLastPathComponent();
            nodo_seleccionado = (DefaultMutableTreeNode) v1;
            
            if (nodo_seleccionado.getUserObject() instanceof vehiculo) {
                eleccionada= (vehiculo) nodo_seleccionado.getUserObject();
                pop_tree.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_tree_vehiculoMouseClicked

    private void pop_favoritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pop_favoritosActionPerformed
        // TODO add your handling code here:
        DefaultComboBoxModel mo = (DefaultComboBoxModel) box.getModel();        
        mo.addElement(eleccionada);
    }//GEN-LAST:event_pop_favoritosActionPerformed

    private void tree_vehiculoValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_tree_vehiculoValueChanged
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_tree_vehiculoValueChanged

    private void pop_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pop_eliminarActionPerformed
        // TODO add your handling code here:
        DefaultTreeModel m = (DefaultTreeModel) tree_vehiculo.getModel(); 
        
        m.removeNodeFromParent(nodo_seleccionado);
        m.reload();
    }//GEN-LAST:event_pop_eliminarActionPerformed

    private void boxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boxItemStateChanged
        // TODO add your handling code here:
        vehiculo ve = (vehiculo) box.getSelectedItem();
        
        Object row[] = new Object[6];
        
        row[0] = ve.getCodigo();
        row[1] = ve.getAnio(); 
        row[2] = ve.getMarca(); 
        row[3] = ve.getModelo(); 
        row[4] = ve.getFechaCreacion(); 
        row[5] = ve.getPrecio();
        
        DefaultTableModel mo = (DefaultTableModel) tabla_vehiculo.getModel(); 
        mo.addRow(row);
    }//GEN-LAST:event_boxItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    DefaultMutableTreeNode nodo_seleccionado;
    vehiculo eleccionada;
    ArrayList<vehiculo> vehiculos = new ArrayList();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_agregar;
    private javax.swing.JComboBox<String> box;
    private javax.swing.JLabel codi;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panel_vehiculo;
    private javax.swing.JPopupMenu pop;
    private javax.swing.JMenuItem pop_agregar;
    private javax.swing.JMenuItem pop_eliminar;
    private javax.swing.JMenuItem pop_favoritos;
    private javax.swing.JMenuItem pop_limpiar;
    private javax.swing.JMenuItem pop_salir;
    private javax.swing.JPopupMenu pop_tree;
    private javax.swing.JTable tabla_vehiculo;
    private javax.swing.JTextField texto_anio;
    private javax.swing.JTextField texto_marca;
    private javax.swing.JTextField texto_modelo;
    private javax.swing.JTextField texto_precio;
    private javax.swing.JTree tree_vehiculo;
    // End of variables declaration//GEN-END:variables
}
